modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/PacketFixer"

[[mixins]]
config="packetfixer.v1_20_2.neoforge.mixins.json"

[[mods]]
modId="packetfixer"
version="${modVersion}"
displayName="PacketFixer"
icon="icon.png"

authors="TonimatasDEV"
description='''
A simple mod to solve various problems with packets.
'''

#[[dependencies.packetfixer]]
#modId="neoforge"
#mandatory=true
#versionRange="[0,)"
#ordering="NONE"
#side="BOTH"
#
#[[dependencies.packetfixer]]
#modId="minecraft"
#mandatory=true
#versionRange="[1.18,1.20.4]"
#ordering="NONE"
#side="BOTH"
